version: '3'
services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - '4563-4599:4563-4599'
      - '8099:8080'
    environment:
      - SERVICES=sns,sqs,iam,ec2
      - DEBUG=1
      - DEFAULT_REGION=us-east-1
      - HOSTNAME=localstack
      - EXTERNAL_HOSTNAME=localstack
      - DATA_DIR=/tmp/localstack/data
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - './.localstack:/tmp/localstack'
      - '/var/run/docker.sock:/var/run/docker.sock'
