version: "3.5"

services:
  sandbank-api:
    container_name: sandbank.api
    ports:
      - "5100:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Demo
    build:
      context: App/BackEnd/SandBank.API/
      dockerfile: Endpoints/Dockerfile
    depends_on:
      - sandbank-db
    networks:
      - sandbank
      - bankengine-external

  sandbank-db:
    image: postgres:latest
    container_name: sandbank.db
    environment:
      POSTGRES_PASSWORD: "password"
      PGDATA: "/var/lib/postgresql/data"
    volumes:
      - sandbank-data:/var/lib/postgresql/data
    networks:
      - sandbank

networks:
  sandbank:
    name: sandbank
  bankengine-external:
    external:
      name: bankengine

volumes:
  sandbank-data:
    external: true
