version: '3'

services:

  sandbank-api:
    container_name: sandbank-api
    ports:
     - "5100:80"
    environment:
     - ASPNETCORE_ENVIRONMENT=Development
    build:
      context: App/BackEnd/SandBank.API/
      dockerfile: ${PWD:-.}/DevOps/Infrastructure/Pipeline/generic-dotnet-Dockerfile
    volumes:
     - ~/.aws/:/root/.aws:ro
    depends_on:
     - db    
   
  db:
    image: postgres:latest
    container_name: db
    environment:
      - POSTGRES_PASSWORD=postgres

  pgAdmin:
    image: dpage/pgadmin4:latest
    container_name: pgAdmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@sandbank.com
      - PGADMIN_DEFAULT_PASSWORD=password
    ports:
      - 9080:80
    depends_on:
     - db
