name: SandBank.API Build & Test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
    - name: Build with dotnet
      run: dotnet build --configuration Release App/BackEnd/SandBank.API/SandBank.API.sln
    - name: Run unit and integration tests
      run: dotnet test --configuration Release App/BackEnd/SandBank.API/SandBank.API.sln
